[package]
name = "rust-ssvm"
version = "0.0.1"
license = "AGPL-3.0"
authors = ["SecondState"]
description = "Rust-SSVM - a Portable EWASM Engine Binding Rust Interface"
edition = "2018"
repository = "https://github.com/second-state/rust-ssvm/"
build="build.rs"

[dependencies]
evmc-sys = { git = "https://github.com/ethereum/evmc", tag = "v6.3.1" }
evmc-vm = { git = "https://github.com/ethereum/evmc/", tag = "v6.3.1" }
evmc-declare = { git = "https://github.com/ethereum/evmc/", tag = "v6.3.1" }
libloading = "0.5"

[build-dependencies]
cmake = "0.1.42"